### PR TITLE
License listed 2x

### PR DESCRIPTION
**Pull request by codejamninja**
This probably sounds OCD, but the same license and copyright information are listed 2x in 2 files.

### CODE REVIEW

**Comment by snuggs** [comment]
Fixes #803 

[How to associate issues with PRs and have them close automagically](https://help.github.com/articles/closing-issues-via-commit-messages)

/cc @jamrizzi @stramel

**Comment by notwaldorf** [comment]
These files are build artifacts. If you change them now, then next time we ship a new release this change will be blown away. @azakus in 0.x we had a gulp thing that just kept one license -- should we bring it back?

**Comment by snuggs** [comment]
@notwaldorf specified in the issue. > https://github.com/webcomponents/webcomponentsjs/issues/803#issuecomment-310947287

**Comment by stramel** [comment]
@notwaldorf That is what I was thinking :+1:

**Comment by jamrizzi** [comment]
@notwaldorf yeah, I didn't notice they were minified till after my pull request. Then I was like, that was brilliant :stuck_out_tongue_closed_eyes:

**Comment by TimvdLippe** [comment]
Closing per https://github.com/webcomponents/webcomponentsjs/issues/803#issuecomment-397813142

**Pull request closed without merging**
