### PR TITLE
initial work to allow webcomponents tests to run with wct and without

### PR DESCRIPTION
**Pull request by eeid26**
This is an initial check in to allow the web components modules tests (CustomElements, HTMLImports, ShadowCSS, ShadowDOM) to run under WCT and without.

My main goal was to make sure the old way (running without wct) still works with no issues. This put restrictions on how much changes I can do and the wct tests are not 100% working. Anyway, this task should happen incrementally.

I also did not want to change the way the tests are written. Some of these tests are not written to handle the way WCT run the tests in a different frame. So, some of the tests fail if the test suite runs with wct. (We can always work on passing these tests after this check in)

Some of the tests also require url parameters to execute different tests like
  'html/colon-host.html',
  'html/colon-host.html?shadow&.html',
So I had to a add .html to the parameters to make wct happy.
  
The ShadowCSS tests are commented in the main runner_wct.html, because it has too many tests that fail under wct because it fails to load some of the tests.

Please review the comments in the wct.conf.js on how to run the tests.

The gulpfile.js might need more work.

gulp test:local does not work for now.

I had to add a special task to run the tests.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for working on this and adding in notes along the way, @eeid26. We'll take a look at this shortly.

**Comment by addyosmani** [comment]
> The ShadowCSS tests are commented in the main runner_wct.html, because it has too many tests that fail under wct because it fails to load some of the tests.

If I'm reading this correctly, you're saying that wct itself is failing to load these tests?

**Comment by eeid26** [comment]
- Merged PR branch with the main branch.
- Removed code coverage tasks from from wct.conf.js. (It can be added later once the tests run successfully with WCT).
- Removed commented code from gulp file. FYI, my changes to the gulp file is just a sample on how to run the tests. For now I mostly run the tests with WCT by invoking WCT directly from the command line. (without using gulp). I did not know how to configure the gulp file to run local only or sauce only. Some other PR can take care of this.
- Enabled the ShadowCSS tests in tests/runner_wct.html, but I execluded some ShadowCSS  test suites from running when invoked by WCT. See tests/ShadowCSS/modules_ShadowCSS.js. The three suites that have been excluded are style-import-base-tag.html, colon-host.html and colon-host.html?shadow.  import-base-tag.html fails on my muchine with WCT and without. It fails even without my changes. The colon-host.html fails under WCT only. I did not make any attempt to fix those tests under WCT, because as I mentioned previously, I did not want running without WCT to change in any way for now.
- 3-4 tests fail in ShadowDom test module when running with WCT (depends on the platform and browser running the tests.) 

sample output of running 'wct --plugin local' on windows 7 with chrome 42
```html
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\projects\webcomponentsjs_eeid>wct --plugin local
Starting Selenium server for local browsers
Selenium server running on port 52353
Web server running on port 52372 and serving from C:\projects
chrome 42                Beginning tests via http://localhost:52372/webcomponentsjs_eeid/tests/runner_wct.html?cli_browser_id=0
404 GET /webcomponentsjs_eeid/tests/foo.wav
chrome 42                ? runner_wct.html » Document » document.registerElement attachedCallback, detachedCallback

  expected 0 to equal 1
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/Document.js:597:0

chrome 42                ? runner_wct.html » Document » document.registerElement get reference, upgrade, rewrap

  expected undefined to be true
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/Document.js:662:0

404 POST /webcomponentsjs_eeid/tests/runner_wct.html?cli_browser_id=0
chrome 42                ? runner_wct.html » Events » window.onerror

  Intentional error
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/events.js:1417:0

404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/import-404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/stuff/sheet.css
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404-1.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404-2.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/load-does-not-exist.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/import-404.html
chrome 42                Tests failed: 3 failed tests
Test run ended in failure: 3 failed tests

chrome 42 (664/2/3)


3 failed tests

```

sample output of running 'wct --plugin sauce' on windows 8.1 with chrome 41
```html
C:\projects\webcomponentsjs_eeid>wct --plugin sauce
Creating Sauce Connect tunnel
Sauce Connect log: C:\Users\EMADEI~1\AppData\Local\Temp\wct115319-10088-s94wph\sc.log
Sauce tunnel active: 205c632b-2477-4f58-8d17-1004d0319357
Web server running on port 55438 and serving from C:\projects
Windows 8.1 chrome 41.0  Beginning tests via http://localhost:55438/webcomponentsjs_eeid/tests/runner_wct.html?cli_browser_id=0
Windows 8.1 chrome 41.0  ? runner_wct.html » Document » document.registerElement attachedCallback, detachedCallback

  expected 0 to equal 1
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/Document.js:597:0

404 GET /webcomponentsjs_eeid/tests/foo.wav
Windows 8.1 chrome 41.0  ? runner_wct.html » Document » document.registerElement get reference, upgrade, rewrap

  expected undefined to be true
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/Document.js:662:0

404 POST /webcomponentsjs_eeid/tests/runner_wct.html?cli_browser_id=0
Windows 8.1 chrome 41.0  ? runner_wct.html » Events » window.onerror

  Intentional error
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/events.js:1417:0

Windows 8.1 chrome 41.0  ? runner_wct.html » Parallel Trees » Visual » insertBefore 2

  expected <d></d> to equal <b></b>
    <unknown> at       expectStructure at /webcomponentsjs_eeid/tests/ShadowDOM/SDTestUtils.js:6:0
    <unknown> at   Context.<anonymous> at /webcomponentsjs_eeid/tests/ShadowDOM/js/paralleltrees.js:419:0

404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/import-404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/stuff/sheet.css
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404-1.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404-2.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/404.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/load-does-not-exist.html
404 GET /webcomponentsjs_eeid/tests/HTMLImports/html/imports/import-404.html
Windows 8.1 chrome 41.0  Tests failed: 4 failed tests
Test run ended in failure: 4 failed tests

Windows 8.1 chrome 41.0 (662/2/4)


4 failed tests


C:\projects\webcomponentsjs_eeid>

```

This check in is intended to change the structure of the files to allow the tests to run with WCT and without. More work is going to be needed to pass all the tests under WCT, fix gulp file and maybe eventually configure the tests to run under WCT only.

**Comment by azakus** [comment]
Ugh, I wish I had seen this PR before I converted the tests to WCT myself.
Sorry for missing this, but now the tests run with WCT (and Travis CI).

**Pull request closed without merging**
