### PR TITLE
Include URL polyfill references in lite/full builds

### PR DESCRIPTION
**Pull request by addyosmani**
(Please don't merge until #196 lands)

Continuing changes for #135, this change specifies the URL polyfill as a build-time dependency before HTML Imports. Given that the use-case for us landing URL polyfill support was Imports, I believe this is the right place.

Feel free to let me know if not.

### CODE REVIEW

**Comment by jmesserly** [comment]
this lgtm too :)

**Comment by addyosmani** [comment]
@garlicnation as we've landed #196, shall I go ahead and rebase this against master?

**Comment by garlicnation** [comment]
@addyosmani goforit!

**Comment by addyosmani** [comment]
@garlicnation rebased against master. Sorry for the delay!

**Pull request merged**
