### PR TITLE
Force Closure to see files as modules by exporting {}

### PR DESCRIPTION
**Pull request by aomarks**
Also remove "use strict" since it's redundant for modules.

### CODE REVIEW

**Comment by azakus** [comment]
@aomarks Does this have to do with some ordering issues with Closure?

**Comment by aomarks** [comment]
In a non-module script, `let customElements = window['customElements']` (which is in post-polyfill.js) shadows the global customElements. Since Closure doesn't know a file is a module unless it imports/exports something, Closure throws an error about redeclaring `customElements`.

**Comment by azakus** [comment]
Gotcha, SGTM

**Comment by azakus** [comment]
Can you also upstream this to master?

**Comment by aomarks** [comment]
> Can you also upstream this to master?

Sure, https://github.com/webcomponents/webcomponentsjs/pull/1033

**Pull request merged**
