### PR TITLE
Add nodeValue to cdata

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM but deferring to @jmesserly. Fyi, about this patch @yyx990803

**Comment by addyosmani** [comment]
Changes LGTM.

**Comment by IntranetFactory** [comment]
Current version also fails in IE11
2015-03-16_1004s

Changing https://github.com/webcomponents/webcomponentsjs/blob/c66aedd142f9dbbc8d1cb196d7e5641b3d657213/src/ShadowDOM/wrappers/CharacterData.js#L31 to
```
set nodeValue(data) {
 this.data=data;
 },
```
solved the issue for me as well.

**Comment by garlicnation** [comment]
@eeid26 @IntranetFactory issue resolved on master.

**Pull request merged**
