### PR TITLE
Add nuget nupkg file

### PR DESCRIPTION
**Pull request by adityapurwa**
The file contains the packed release for NuGet gallery that can be used in Visual Studio. It includes the latest dist version of the repository.

### CODE REVIEW

**Comment by addyosmani** [comment]
@adityapurwa we discussed NuGet support in #166. Is there a reason the package contents in your PR need to land in this repo vs managing a NuGet package for the polyfills separately?

**Comment by adityapurwa** [comment]
@addyosmani I proposed this file in case other people want to track the nupkg file from the repo too. If you think that it is not neccessary for other people to track, i'll handle the nuget management on another repo.

**Comment by addyosmani** [comment]
Thanks again for proposing this. imo, we should track the nupkg file and manage it in a separate repo to keep things lean and focused in this one.

**Comment by adityapurwa** [comment]
@addyosmani Ok, i'll set up a separate repo to keep track of the NuGet package.

**Pull request closed without merging**
