### PR TITLE
fixes #285, getElementById on DocumentFragment

### LINKED ISSUE #285: template.content.getElementById() not wrapped
If you have a template element, calling `.content.getElementById("id")` will return an unwrapped node.

### PR DESCRIPTION
**Pull request by jmesserly**
This fixes getElementById which was never implemented correctly except on ShadowRoot. Now it works on Document and DocumentFragment.

### CODE REVIEW

**Comment by jmesserly** [comment]
@addyosmani -- do you mind reviewing this?

**Comment by addyosmani** [comment]
Changes LGTM. Thanks for including tests!. I'll do some more thorough checks in the morning before landing this.

@kevincox could you verify this fix addresses the issue you raised in #285?

**Comment by kevincox** [comment]
Yes, this fixes it. :+1:

**Comment by addyosmani** [comment]
LGTM.

**Pull request merged**
