### PR TITLE
Add an activeElement getter for #110

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM.

**Comment by jmesserly** [comment]
Hmmm. This doesn't respect the ShadowDOM encapsulation right? 
https://github.com/webcomponents/webcomponentsjs/issues/110
http://w3c.github.io/webcomponents/spec/shadow/#active-element

(apologies if I'm missing some context)

**Comment by garlicnation** [comment]
This is causing a build error, backing out for now.

@jmesserly, no, it doesn't, but this seemed like a decent solution to prevent the workarounds needed from #110. I'd much prefer to fix this in a spec-compliant way.

**Comment by addyosmani** [comment]
Ah. Sorry for not catching that this broke SD encapsulation. I should have during review.

**Comment by garlicnation** [comment]
@jmesserly Thanks for the spec link. It should be easy to fix this up.

**Pull request merged**
