### PR TITLE
Reduces the package output

### LINKED ISSUE #928: [v2] NPM package should be stripped
[Browse package here](https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0-beta.2/)

Expected: it does not include tests/, and other extraneous files.

Actual: it includes artifacts in the package.

### PR DESCRIPTION
**Pull request by abdonrd**
Fixes #928.

This reduces the package size.

### CODE REVIEW

**Comment by web-padawan** [comment]
Consider using `"files"` property instead to specify the included files explicitly: https://docs.npmjs.com/files/package.json#files

**Comment by abdonrd** [comment]
@web-padawan should be like this, right?

```json
  "files": [
    "bundles/**/*",
    "entrypoints/**/*",
    "custom-elements-es5-adapter.js",
    "webcomponents-bundle.js",
    "webcomponents-bundle.js.map",
    "webcomponents-loader.js"
  ]
```

Or am I leaving something?

**Comment by azakus** [comment]
Hmm, is package size a concern?

**Comment by abdonrd** [comment]
@azakus Less is better. And we would save ourselves problems like having to ignore the `gulpfile.js` in the PSK and in the other templates.

**Comment by abdonrd** [comment]
Rebased on master and updated PR branch! :)

**Comment by keanulee** [comment]
+1 on reducing package size. This seems to be what most other npm packages do ([request](https://github.com/request/request/blob/master/package.json), [redux](https://github.com/reactjs/redux/blob/master/package.json), [sw-precache](https://github.com/GoogleChromeLabs/sw-precache/blob/master/package.json), and more).

**Comment by TimvdLippe** [comment]
Thanks!

**Pull request merged**
