### PR TITLE
Passes detailed import load\error info to callback

### PR DESCRIPTION
**Pull request by pflannery**
fixes [polymer/#1184](http://github.com/polymer/polymer/issues/1184)
fixes [polymer/#1127](http://github.com/polymer/polymer/issues/1127)

Example usage:
```js
Polymer.import(["http://url1", "http://url2", "http://etc.."], function(detail) {
  var hasAllImports = detail.allImports.length > 0;
  var hasLoadedImports = detail.loadedImports.length > 0;
  var hasErrorImports = detail.errorImports.length > 0;
}
```

### CODE REVIEW

**Comment by pflannery** [comment]
related to https://github.com/Polymer/polymer/pull/1186

**Comment by addyosmani** [comment]
Thanks. Can we expand the unit tests to cover the extra details being passed to the callback?

**Comment by pflannery** [comment]
Had to amend whenReady callback to pass event detail to HTMLImportsLoaded so that I could create the tests.

Added three tests
- tests/HTMLImports/html/dynamic-all-imports-detail.html
- tests/HTMLImports/html/dynamic-errors-detail.html
- tests/HTMLImports/html/dynamic-loaded-detail.html

They check ```allImports, errorImports and loadedmports``` are reporting the expected detail in the HTMLImportsLoaded  event.

**Comment by addyosmani** [comment]
Review of the initial implementation LGTM. I haven't reviewed the tests yet.

**Comment by rossross** [comment]
+1

Being able to tell if an import failed is absolutely essential

**Comment by addyosmani** [comment]
I've run through the unit tests in our target browsers (directly, not through wct) and they are passing for me. Delegating to @garlicnation for a final review before merge.

**Comment by pflannery** [comment]
@addyosmani I've reformtatted the loop and left the test loops formatted like the original test I copied it from. I've also renamed the failing test import to "load-does-not-exist.html" PTAL

Let me know if you want me to squash these commits back to one.

**Comment by addyosmani** [comment]
> Let me know if you want me to squash these commits back to one.

Yes please! Thanks for addressing the comments so far!

**Comment by pflannery** [comment]
@addyosmani done!

**Comment by pflannery** [comment]
@addyosmani any love for this :) ?

**Comment by addyosmani** [comment]
@garlicnation I've tested this to sufficiently feel it can be merged without causing regressions. Going ahead with landing it, but I'll do some further testing next week and report back/back out if it causes any unwanted behaviour.

**Comment by pflannery** [comment]
:+1: thanks

**Pull request merged**
