### PR TITLE
Ensure newly created templates have content

### PR DESCRIPTION
**Pull request by kevinpschaaf**
Part of fix for Polymer/polymer#1500

### CODE REVIEW

**Comment by azakus** [comment]
My only concern is that this will break the `decorate` function for templates that were created by script before `DOMContentLoaded`.

@garlicnation thoughts?

**Comment by kevinpschaaf** [comment]
@azakus the `content` created by decorate at DOMContentLoaded won't stomp on `content` created by this `createElement` addition (it existence checks here: https://github.com/webcomponents/webcomponentsjs/blob/ensure-tmpl-content/src/Template/Template.js#L28).

**Comment by kevinpschaaf** [comment]
I'll make a change so that template children are moved into `content` even when the template is created imperatively, so that you could `innerHTML = ...` an imperatively-created template and have decorate move them into the content at DOMContentLoaded time.

**Comment by garlicnation** [comment]
Merged.

**Pull request closed without merging**
