### PR TITLE
element.matches() fixes

### PR DESCRIPTION
**Pull request by nazar-pc**
Support for `:host`, `::content` and similar selectors in `element.matches()`

### CODE REVIEW

**Comment by nazar-pc** [comment]
Without this patch will fail with `An invalid or illegal string was specified`

**Comment by addyosmani** [comment]
Do you have a test case that fails without this patch in place?

**Comment by nazar-pc** [comment]
Is jsfiddle ok for demonstration (webcomponents.js included from polymer-project.org)?
http://jsfiddle.net/u6vdvd5q/
It will fail to run actually, look into console for `An invalid or illegal string was specified`

Just on any page with WebComponents.js write something like `document.querySelector('whatever').matches(':host *')` and it will break.

However, with patched version it will work, the same example with patched build embedded:
http://jsfiddle.net/u6vdvd5q/1/

**Comment by addyosmani** [comment]
Confirmed via your test case. @garlicnation do we want to land this?

**Comment by jmesserly** [comment]
@addyosmani IMO, it's great to support these. It's kind of strange that querySelector and matches are inconsistent right now.

A few high level comments on the change:

it would be nice to put the logic in https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/querySelector.js so it's all grouped together

also, https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/ShadowRenderer.js and querySelector both rely on el.matches() ... is it intended that they're now calling this polyfilled method? I worry that we're checking for something twice. But maybe this actually fixes some bugs. (apologies, I don't have the querySelector code loaded into my brain anymore, so off hand not sure how they'll interact :) ). Finally, I'd double check that this doesn't hurt performance of qS/qSA since matches is polyfilled now, and it will be computing that polyfilled selector string over and over.

**Comment by jmesserly** [comment]
btw, an easy way to avoid my concerns about interactions would be to change the existing el.matches calls in ShadowDOM code to call originalMatches.

**Comment by nazar-pc** [comment]
Currently `originalMatches` is local variable and not available anywhere outside its scope.

**Comment by jmesserly** [comment]
yeah, no worries about that though, it can be easily saved:

```js
scope.originalMatches = originalMatches;
```

**Comment by addyosmani** [comment]
@nazar-pc Want to go ahead and update your PR to make `originalMatches` available outside its scope? It would be great to land this once @jmesserly's comments have been addressed.

**Comment by nazar-pc** [comment]
Done.
By the way I found that `document.querySelector('div::shadow div')` doesn't work with polyfill, while working natively in Chromium. That is why I've fixed that too and added tests for that.

Both `querySelector` and `ShadowRenderer` use overridden version of `.matches()` because a lot of tests fail with original.

**Comment by nazar-pc** [comment]
Sorry about mixing `querySelector` fix in this pull request, but they are really very close.

**Comment by jmesserly** [comment]
> Sorry about mixing querySelector fix in this pull request, but they are really very close.

no worries! taking a look now

**Comment by jmesserly** [comment]
LGTM. thank you!

**Pull request merged**
