### PR TITLE
Upgrade es6-promise

### LINKED ISSUE #794: vertx dependency in webcomponents-lite.js
What is this `vertx` and why is it required in try-catch within `webcomponents-lite.js` ? there is nothing like that in dependencies of this project

https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-lite.js#L94

### PR DESCRIPTION
**Pull request by mroem**
- Update `es6-promise` to `4.2.4` to fix [unresolved `vertx`](https://github.com/stefanpenner/es6-promise/issues/305)

Fixes #794 

*UPDATE*
- Reverting upgrade
- Use `patch-package` to resolve issue using related fix: see [#305 on `es6-promise`](https://github.com/stefanpenner/es6-promise/pull/323)

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Hm, although I just inspected the Travis build log and it does seem related to `Promise`. Maybe it actually broke with this upgrade 😢

**Comment by mroem** [comment]
*UPDATE*

- Use patch-package to resolve issue using related fix: see #305 on es6-promise

**Comment by TimvdLippe** [comment]
I would rather not have a private patch applied, as that is brittle going forward with later versions of the polyfill. Rather, we should investigate why the build started failing and report issues to the author to get them resolved.

**Comment by mroem** [comment]
_UPDATE_

The es6-promise package needs to be transpiled as it uses Classes which causes `google-closure-compiler` to nullify some properties in ADVANCED mode.
See `Static class functions can be erroneously removed in ADVANCED mode` [#2763](https://github.com/google/closure-compiler/issues/2763)

**Comment by TimvdLippe** [comment]
@mroem I have changed the base to v2. Could you resolve the conflicts and try again? v2 should be working on Travis (barring some test failures).

I do want to get this PR in, but I think we have to wait till the v2 work has been done before making this change. Thank you for your patience and development on this!

**Comment by mroem** [comment]
@TimvdLippe 
How much work is still needed on v2?
I kind of need this change urgently, and it would solve this issue for all the people using v1.
I‘m happy to put a second Pull request up for v2, so that we can merge this into v1

**Comment by NMinhNguyen** [comment]
@TimvdLippe could you elaborate on the reasons for having to wait till the v2 work has been done?

**Comment by TimvdLippe** [comment]
It will be released next week. New additions should be added there, to
prevent diverging the two versions too much.

**Comment by NMinhNguyen** [comment]
> to prevent diverging the two versions too much.

@TimvdLippe correct me if I’m misunderstanding, but if this change was applied to both branches, there’d be no divergence, right? Good to hear v2 is coming soon though 🙂

**Comment by mroem** [comment]
@TimvdLippe @azakus @NMinhNguyen any update on this?

**Comment by TimvdLippe** [comment]
Test failures are the same on this branch and on master, so this change seems fine to me. Thanks @mroem for keeping this PR up-to-date!

**Pull request merged**
