### PR TITLE
Massively clean up `v1` branch

### PR DESCRIPTION
**Pull request by notwaldorf**
Tests in Polymer with this branch: https://github.com/Polymer/polymer/pull/4220

Changes in this gory PR (sorry not sorry 🤷‍♀️)
* [x] branch master for "v0" (v1 branch will eventually be moved to master): https://github.com/webcomponents/webcomponentsjs/tree/v0
* [x] remove unused polyfills for v1
  * [x] MutationObserver
  * [x] ShadowCSS
  * [x] ShadowDOM
  * [x] WeakMap
* [x] separate polyfills to separate repos
  * [x] HTMLImports (coordinate with v1 HTMLImports owner)
  * [x] Template
  * [x] URL (maybe?) Moved `Polymer/URL` to `webcomponents/URL` and ported the 2 changes
  * [x] "Platform" polyfill (dom+lang minus unneeded stuff): https://github.com/webcomponents/webcomponents-platform
    * constructable events
    * ES6 stuff (Array.from, Object.assign)
  * [x] Remove code for unneeded stuff:
    * Function.prototype.bind
    * requestAnimationFrame
    * performance.now
    * [x] Promise
    * [x] legacy CustomElements.takeRecords
  * [x] Leave as wcjs-specific code:
    * flag handling (pre-polyfill)
    * WebComponentsReady event `post-polyfill.js` (TBD -- needs discussion)
    * unresolved styling `unresolved.js` (TBD -- needs discussion)
* [~] "everything together" build
    * Sort of: there's an "everything `webcomponents-lite.js` but no actual build steps
* [~] normalize test & build infrastructure between all separate polyfill repos
    * Sort of: there are tests, but they're not the best, but they're green

### CODE REVIEW

**Comment by antonmes** [comment]
@tomalec ShadowDOM was moved to it's own repo https://github.com/webcomponents/shadydom

**Comment by notwaldorf** [comment]
@tomalec Shadow DOM is not shady DOM. Shady DOM lives happily in its own repo, and is being updated for v1. The current Shadow DOM polyfill only works in v0 (so certainly doesn't work in the v1 branch), and is far less needed in v1 as most browsers are implementing the shadow DOM spec. Hope this clears up the confusion!

**Comment by notwaldorf** [comment]
Wahhhhh this passes on my iOS9 simulator:
screen shot 2017-01-04 at 5 28 19

**Comment by sorvell** [comment]
Cleanup cruft here: https://github.com/webcomponents/webcomponentsjs/blob/v1-cleanup/src/boot-lite.js#L53.

Let's consider removing `[unresolved]` from `body` after this: https://github.com/webcomponents/webcomponentsjs/blob/v1-cleanup/src/post-polyfill.js#L17.

**Comment by sorvell** [comment]
Can we identify who needs `URL`? If it's not core to web components perhaps it can be eliminated since it's a good chunk of code.

**Comment by notwaldorf** [comment]
This fails on IE11 because `<template>` doesn't seem to be inert?

**Comment by tomalec** [comment]
Thanks @notwaldorf,
You don't plan to provide more strict Shadow DOM v1 polyfill, do you?
Does old v0 Shadow DOM Polyfill collides with v1 Shady DOM, or could I run them side by side?
I'd like to keep some of my vanilla elements in v0 (or some kind of hybrid) and upgrade Polymer to 2.0.

**Comment by notwaldorf** [comment]
Alright @sorvell, these tests are green, and the polymer tests using this branch (https://github.com/Polymer/polymer/pull/4220) are green, i'm shipping this.

**Pull request merged**
