### PR TITLE
Add missing dependencies for fresh builds

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Comment by azakus** [comment]
@jmalonzo `npm install` in a clean checkout seems to work just fine. Why is this necessary to add to the top level `package.json`?

**Comment by jmalonzo** [comment]
`gulp` failed on my machine with missing dependencies after `npm install`, hence this PR. Is it just me?

**Comment by azakus** [comment]
Working for me. Can you give a few more details of your environment?

`npm ls -g --depth=0` and `node -e 'console.log(process.versions)'` output would be a good start.

**Comment by jmalonzo** [comment]
@azakus had to redo it again but it seems to be working now. I'm not sure how I ended up with missing deps but all good now. Thanks for your help!

**Pull request closed without merging**
