### PR TITLE
Move WeakMap polyfill to the beginning.

### PR DESCRIPTION
**Pull request by threeday0905**
* webcomponents-lite.js - WeakMap polyfill may be executed before MutationObserver
* webcomponent.js - Move WeakMap polyfill outside condition statement.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for your PR. Could you sign our [CLA](https://cla.developers.google.com/clas) so we can move ahead with reviewing your changes?

**Comment by garlicnation** [comment]
This looks like it could be related to #210.

**Comment by threeday0905** [comment]
Hi, 

CLA has been signed.

I think this issue is same as #210. 

In this pr, I just update **build.json** and **build-lite.json** to move WeakMap polyfill in front of the file, the reason as following.

---
In current *webcomponents-lite.js* build, WeakMap is polyfill after than MutationObserver. But MutationObserver is depend on WeakMap, like below: 



    (function(global) {
        var registrationsTable = new WeakMap();
        var setImmediate;
    
    
    //.... after 300 lines ...
    
    if (typeof WeakMap === "undefined") {
      (function() {

So if browser does not support WeakMap (like older version chrome, in china), it will cause some exception. And if swap WeakMap and MutationObserver, the code works good.

---

In *webcomponents.js* build, WeakMap polyfill is inside a shadow dom block like below:  

    if (WebComponents.flags.shadow) {
      if (typeof WeakMap === "undefined") {
          // code is here
      }
    }
    
I think WeakMap polyfill and ShadowDom polyfill is independent module, so I update the build.json to move WeakMap outside ShadowDom polyfill.

**Comment by addyosmani** [comment]
@paulie4 would this address any of the issues you were seeing?

**Comment by threeday0905** [comment]
oops, I forgot to switch to my personal account. I will close this PR.

**Comment by paulie4** [comment]
@addyosmani, yes it does, thanks @threeday0905!

**Comment by threeday0905** [comment]
@paulie4, actually I close this pr without merge. should I reopen this pr?

**Comment by paulie4** [comment]
Why did you close the pull request?

**Comment by threeday0905** [comment]
I use I am using the other email (not github account) to commit this change. So that I close this pr and revert that commit.

If it is ok, free feel to reopen this pr and merge it.

**Comment by threeday0905** [comment]
@paulie4 

I am using the other email (not github account) to commit this change. So that I close this pr and revert that commit.

If it is ok, free feel to reopen this pr and merge it.

**Comment by paulie4** [comment]
I am not a contributor to this project, so someone else would need to merge this pull request (and reopen it, if necessary).

**Comment by saranrapjs** [comment]
This issue (in Safari 7, WeakMap being undefined) remains an issue.  @threeday0905 are you planning on committing this with a different GitHub account?  If not, does someone else need to create a new pull request with these changes?

**Comment by threeday0905** [comment]
@saranrapjs, I had created another PR based on latest master branch, #240.

**Pull request closed without merging**
