### PR TITLE
[1/2] Use https://webcomponents.org/polyfills as homepage

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@valdrinkoshi, @azakus, please merge this pull request.

**Comment by notwaldorf** [comment]
Needs a rebase

**Comment by notwaldorf** [comment]
As a side note: is there a reason why you haven't sent this at the same time as the `package.json` PR, or your other 9 PRs that just clean up random fields in `package/bower.json`? Spamming my inbox with emails is just going to make it harder for anyone (me) to keep track of these PRs 😢

**Comment by FluorescentHallucinogen** [comment]
I've used the "one change — one pull request" principle. Using separate pull requests for each changes, you can close some of them, but merge the rest. I thought it was a good idea. Sorry.

**Comment by FluorescentHallucinogen** [comment]
> Needs a rebase

Done.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf, @azakus Any progress?

**Comment by TimvdLippe** [comment]
Since we no longer have `bower.json`, I am closing this PR.

**Pull request closed without merging**
