### PR TITLE
Add a file with compiler externs for the API exposed by the polyfills.

### PR DESCRIPTION
**Pull request by rictic**
/cc @azakus

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@rictic is this still something you would like to pursue?

**Comment by rictic** [comment]
I think this is desirable, yeah. I don't have rights to assign a reviewer, but I think Dan would be a good one for this.

**Comment by azakus** [comment]
Would it be better for this to go into HTMLImports?

**Comment by valdrinkoshi** [comment]
FYI there is already one in html-imports https://github.com/webcomponents/html-imports/blob/master/externs/html-imports.js

**Comment by azakus** [comment]
@valdrinkoshi maybe port this one over there because it has comments 😁

**Comment by valdrinkoshi** [comment]
Done https://github.com/webcomponents/html-imports/pull/80

**Comment by rictic** [comment]
Closed in favor of webcomponents/html-imports#80

**Pull request closed without merging**
